# Generated by Django 2.2.3 on 2019-07-19 21:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Citation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('citation', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Master',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='Nom')),
                ('age', models.DateField(auto_now_add=True)),
                ('location', models.CharField(max_length=250)),
                ('occupation', models.CharField(max_length=250)),
                ('motto', models.CharField(max_length=500)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='ProExperience',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=100, verbose_name='Entreprise')),
                ('company_logo', models.ImageField(upload_to='images/')),
                ('function', models.CharField(max_length=250, verbose_name='Poste occupée')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('master', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='page.Master')),
            ],
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diploma', models.CharField(max_length=500, verbose_name='Diplôme')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('school_logo', models.ImageField(upload_to='images/')),
                ('cursus_status', models.CharField(max_length=7)),
                ('master', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='page.Master')),
            ],
        ),
    ]
